### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by gbenhaim**
1. Fix "docker-storage" configuration.
2. Stop deploying Kubevirt on Openshift in the CI flow (the current flow is a bit hacky and take a lot of 
    time, let's focus on the APB way).
3. Use Openshift 3.7 RC.

### CODE REVIEW

**Comment by gbenhaim** [comment]
ci test please

**Comment by gbenhaim** [comment]
ci test please

**Comment by gbenhaim** [comment]
ci test please

**Comment by gbenhaim** [comment]
ci test please

**Comment by gbenhaim** [comment]
ci merge please

**Comment by lukas-bednar** [comment]
@gbenhaim Thanks for making this repo to run with standard ci.
Can you please point me where I can see some logs where the playbook from this repository was executed ?
I am searching in content of following link, but I can not find it.
http://jenkins.ovirt.org/blue/organizations/jenkins/kubevirt-incubator_kubevirt-ansible_standard-check-pr/detail/kubevirt-incubator_kubevirt-ansible_standard-check-pr/14/pipeline/117

**Comment by lukas-bednar** [comment]
@gbenhaim no problem, I found it: http://jenkins.ovirt.org/blue/rest/organizations/jenkins/pipelines/kubevirt-incubator_kubevirt-ansible_standard-check-pr/runs/14/nodes/117/steps/165/log/?start=0

**Pull request merged**
